[PHP]
memory_limit = 512M
max_execution_time = 60
upload_max_filesize = 20M
post_max_size = 25M
date.timezone = UTC
expose_php = Off

; Performance / Realpath cache (Symfony recommendations)
realpath_cache_size = 4096K
realpath_cache_ttl = 600

; OPcache (Symfony recommendations)
[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
opcache.save_comments = 1
opcache.fast_shutdown = 1
 
; Xdebug 3
[xdebug]
xdebug.mode = debug,develop
xdebug.start_with_request = trigger
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.idekey = PHPSTORM
xdebug.log = /tmp/xdebug.log
